// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddBookForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-2xl mx-auto bg-white p-8 rounded-xl shadow-md mt-10\"><h2 class=\"text-2xl font-bold mb-6\">Add New Library Book</h2><form hx-post=\"/add-book\" class=\"space-y-4\"><input type=\"text\" name=\"title\" placeholder=\"Book Title\" class=\"w-full border p-2 rounded\" required> <input type=\"text\" name=\"author\" placeholder=\"Author\" class=\"w-full border p-2 rounded\" required> <input type=\"text\" name=\"isbn\" placeholder=\"ISBN\" class=\"w-full border p-2 rounded\" required> <input type=\"text\" name=\"category\" placeholder=\"Category\" class=\"w-full border p-2 rounded\" required><div class=\"grid grid-cols-2 gap-4\"><input type=\"number\" name=\"year\" placeholder=\"Year\" class=\"border p-2 rounded\" required> <input type=\"number\" name=\"copies\" placeholder=\"Total Copies\" class=\"border p-2 rounded\" required></div><button type=\"submit\" class=\"w-full bg-slate-900 text-white py-3 rounded-lg font-bold\">ADD BOOK</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
