// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"h-screen w-screen flex items-center justify-center bg-library relative\"><div class=\"absolute inset-0 bg-black/50 backdrop-blur-sm z-0\"></div><div class=\"relative z-10 w-full max-w-md bg-white p-10 rounded-2xl shadow-2xl\"><div class=\"text-center mb-8\"><h2 class=\"text-3xl font-extrabold text-slate-900\">Welcome Back</h2><p class=\"text-green-500 font-medium\">Please enter your library credentials</p></div><form hx-post=\"/login\" hx-target=\"#login-err\" class=\"space-y-6\"><div><label class=\"block text-sm font-semibold text-slate-700 mb-2\">Email Address</label> <input type=\"email\" name=\"email\" class=\"w-full px-4 py-3 border border-slate-200 rounded-lg text-slate-900 focus:ring-2 focus:ring-green-400 outline-none bg-white\" required></div><div><label class=\"block text-sm font-semibold text-slate-700 mb-2\">Password</label> <input type=\"password\" name=\"password\" class=\"w-full px-4 py-3 border border-slate-200 rounded-lg text-slate-900 focus:ring-2 focus:ring-green-400 outline-none bg-white\" required></div><div id=\"login-err\" class=\"text-red-500 text-sm italic\"></div><button type=\"submit\" class=\"w-full bg-green-400 text-slate-900 font-bold py-3 rounded-lg hover:bg-green-500 transition-all\">LOGIN TO ACCOUNT</button></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
